# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_delete_testmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
